apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: k8s-basics
  labels:
    app: notify-service-nginx-deploy
spec:
  type: NodePort
  selector:
    app: notify-service-nginx-deploy
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30083
