apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-event
  namespace: k8s-basics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify-event
  template:
    metadata:
      labels:
        app: notify-event
    spec:
      initContainers:
        - name: wait-for-php
          image: alpine:3.18
          command: ['sh', '-c', 'apk add --no-cache netcat-openbsd && until nc -z notify-php-service 9000; do echo "Waiting for notify-php-service..."; sleep 2; done;']
      containers:
        - name: registry-event
          image: atrem2023/notification-service:amd64
          command: ["php", "artisan", "app:notification-event"]
          env:
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_PORT
            value: "5672"    