apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-notify-event
  namespace: k8s-basics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-notify-event
  template:
    metadata:
      labels:
        app: auth-notify-event
    spec:
      initContainers:
        - name: wait-for-php
          image: alpine:3.18
          command: ['sh', '-c', 'apk add --no-cache netcat-openbsd && until nc -z php-service 9000; do echo "Waiting for php-service..."; sleep 2; done;']
      containers:
        - name: notify-event
          image: atrem2023/auth-service-v2:amd64
          command: ["php", "artisan", "app:notify-event"]         
          env:
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_PORT
            value: "5672"