apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-queue-worker
  namespace: k8s-basics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-queue-worker
  template:
    metadata:
      labels:
        app: billing-queue-worker
    spec:
      initContainers:
        - name: wait-for-php
          image: alpine:3.18
          command: ['sh', '-c', 'apk add --no-cache netcat-openbsd && until nc -z billing-php-service 9000; do echo "Waiting for billing-php-service..."; sleep 2; done;']
      containers:
        - name: queue-worker
          image: atrem2023/billing-service-v2:amd64
          command: ["php", "artisan", "queue:work", "--verbose", "--tries=3", "--timeout=60"]
          env:
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_PORT
            value: "5672"           
