apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service-nginx-deploy
  namespace: k8s-basics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service-nginx-deploy
  template:
    metadata:
      labels:
        app: delivery-service-nginx-deploy
    spec:
      containers:
        - name: nginx
          image: atrem2023/app-nginx:amd64
          ports:
            - containerPort: 80
          volumeMounts:
            - name: delivery-service-nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf          
      volumes:
        - name: delivery-service-nginx-config
          configMap:
            name: delivery-service-nginx-config
