apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-php
  namespace: k8s-basics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-php
  template:
    metadata:
      labels:
        app: stock-php
    spec:
      containers:
        - name: php
          image: atrem2023/stock-service-v2:amd64
          ports:
            - containerPort: 9000
          env:
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD           
            