apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-event
  namespace: k8s-basics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-event
  template:
    metadata:
      labels:
        app: stock-event
    spec:
      initContainers:
        - name: wait-for-php
          image: alpine:3.18
          command: ['sh', '-c', 'apk add --no-cache netcat-openbsd && until nc -z stock-php-service 9000; do echo "Waiting for stock-php-service..."; sleep 2; done;']
      containers:
        - name: stock-event
          image: atrem2023/stock-service-v2:amd64
          command: ["php", "artisan", "app:stock-event"]      
          env:
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_PORT
            value: "5672"